spring.application.name=contacts-api
kenect.api.base-url=https://candidate-challenge-api-489237493095.us-central1.run.app
kenect.api.contacts-path=/api/v1/contacts
kenect.api.token=J7ybt6jv6pdJ4gyQP9gNonsY
